### ISSUE TITLE
feat: Liquibase Dialect

### ISSUE THREAD

**Issue by KirillKurdyukov** [ydb-platform/ydb-java-dialects#31]
https://contribute.liquibase.com/code/

- [x] Initial module liquibase + started develop (create YdbDatabase.java + CreateIndexGeneratorYdb.java) #32 
- [x] CreateTable sql generator https://github.com/ydb-platform/ydb-java-dialects/pull/33
- [x] Support StandardLockService (may be use coordination service in future) https://github.com/ydb-platform/ydb-java-dialects/pull/36
- [x] Support YDB Types (e.g CHAR change to Text, integer change to Int32) https://github.com/ydb-platform/ydb-java-dialects/pull/34
- [x] SqlGenerators (for all SqlStatements from liquibase-core) to be implemented: https://github.com/ydb-platform/ydb-java-dialects/pull/37

1. YDB doesn't support AddAutoIncrementStatement. - **SOLVED** [AddAutoIncrementGenerator - database.supportsAutoIncrement() return false]
2. YDB doesn't support AddCheckConstraintStatement. - **SOLVED** [supports(AddCheckConstraintStatement var1, Database var2) return false]
3. YDB supports AddColumnStatement. - AddColumnGeneratorYdb.class with custom validation - **SOLVED**
4. YDB doesn't support AddDefaultValueStatement. **SOLVED** [throw validationError]
5. YDB doesn't support AddForeignKeyConstraintStatement. **SOLVED** [throw validationError]
6. YDB doesn't support AddPrimaryKeyStatement. **SOLVED** [throw validationError]
7. YDB doesn't support AddUniqueConstraintStatement. **SOLVED** [throw validationError]
8. YDB doesn't support AlterSequenceStatement. **SOLVED** [ydbDatabase.supportsSequences() == false <--> ok]
9. Dummy SQL generator for BatchDmlExecutablePreparedStatement provided by liquibase-core. **OK**
10. ClearDatabaseChangeLogTableStatement. - **OK** [DELETE FROM TABLE - valid YQL]
11. CommentStatement. - **OK** [-- comment - valid YQL]
12. CopyRowsStatement - **OK** [INSERT INTO TABLE(A, B) SELECT A, B FROM A - valid YQL]
13. CreateIndexGenerator - **SOLVED** (create YdbDatabase.java + CreateIndexGeneratorYdb.java) #32
14. CreateSequenceStatement - **OK** [ydbDatabase.supportsSequences() == false <--> ok]
15. YDB doesn't support CreateProcedureStatement - **SOLVED** [throw validationError]
16. DeleteStatement - **OK** [DELET FROM TABLE WHERE A = 1 - valid YQL]
17. DropIndexStatement - **SOLVED** [DropIndexGeneratorYdb]
18. RenameTableStatement - **SOLVED** [RenameTableGeneratorYdb]
19. YDB doesn't support RenameColumnStatement brrrr. -  **SOLVED** [throw validationError]
20. YDB doesn't support DropPrimaryKeyStatement. - [throw validationError]
21. YDB doesn't support GetViewDefinitionStatement. - [throw validationError]
- [x] #39
- [x] #45
- [x] #49
- [x] #50

**Comment by KirillKurdyukov** [comment]
- [ ] Initial module liquibase + started develop (create YdbDatabase.java + CreateIndexGeneratorYdb.java) #32

**Comment by sancho20021** [comment]
The world needs this stuff! Commoooon let's goo

**Comment by KirillKurdyukov** [comment]
Done!
